# Generated by Django 3.0.6 on 2020-06-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('str_time', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'db_table': 'tb_demo',
            },
        ),
        migrations.CreateModel(
            name='ChilDemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('father_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='demo_service.DemoModel')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'db_table': 'tb_chil_demo',
            },
        ),
    ]
