# Generated by Django 2.2.3 on 2020-04-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'db_table': 'tb_demo',
            },
        ),
    ]
