# Generated by Django 3.0.6 on 2020-06-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_service', '0002_childemomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='str_time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
