# Generated by Django 3.0.6 on 2020-06-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_service', '0003_demomodel_str_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='str_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
