# Generated by Django 3.0.6 on 2020-06-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_service', '0004_auto_20200607_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='str_time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
