# Generated by Django 3.0.6 on 2020-06-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasedetail',
            name='parameters_index',
        ),
    ]
