# Generated by Django 3.0.6 on 2020-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestreport',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='apitestreportdetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='busimodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='host',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='interface',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态（1删除，0未删除）'),
        ),
    ]
