# Generated by Django 3.0.6 on 2020-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0002_auto_20200603_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestreportdetail',
            name='case_id',
            field=models.TextField(verbose_name='所属用例id'),
        ),
        migrations.AlterField(
            model_name='apitestreportdetail',
            name='report_id',
            field=models.TextField(verbose_name='所属报告id'),
        ),
        migrations.AlterField(
            model_name='busimodel',
            name='project_id',
            field=models.TextField(verbose_name='所属项目id'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project_id',
            field=models.TextField(verbose_name='所属项目id'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='busi_id',
            field=models.TextField(verbose_name='所属业务id'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='project_id',
            field=models.TextField(verbose_name='所属项目id'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='plan_id',
            field=models.TextField(verbose_name='所属计划id'),
        ),
        migrations.AlterField(
            model_name='testcasedetail',
            name='case_id',
            field=models.TextField(verbose_name='所属用例id'),
        ),
        migrations.AlterField(
            model_name='testcasedetail',
            name='path_id',
            field=models.TextField(verbose_name='请求资源地址'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='project_id',
            field=models.TextField(verbose_name='所属项目id'),
        ),
        migrations.AlterModelTable(
            name='interface',
            table='tb_interface',
        ),
    ]
