# Generated by Django 3.0.6 on 2020-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0002_auto_20200726_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busimodel',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='checkpoint',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='expression_status',
            new_name='is_expression',
        ),
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='mock_status',
            new_name='is_mock',
        ),
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='status',
            new_name='is_status',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='status',
            new_name='is_status',
        ),
    ]
