# Generated by Django 3.0.6 on 2020-06-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0002_remove_testcasedetail_parameters_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='header',
            new_name='headers',
        ),
    ]
