# Generated by Django 3.0.6 on 2020-06-04 08:33

import apps.test_platform.enumeration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0003_auto_20200603_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestreport',
            name='task_status',
            field=models.CharField(choices=[(apps.test_platform.enumeration.TaskStatus['WAIT'], apps.test_platform.enumeration.TaskStatus['WAIT']), (apps.test_platform.enumeration.TaskStatus['EXECUTION'], apps.test_platform.enumeration.TaskStatus['EXECUTION']), (apps.test_platform.enumeration.TaskStatus['FINISH'], apps.test_platform.enumeration.TaskStatus['FINISH'])], max_length=32, verbose_name='任务状态（1、等待执行2、执行中3、执行完成）'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='method',
            field=models.CharField(choices=[(apps.test_platform.enumeration.RequestMethod['Get'], apps.test_platform.enumeration.RequestMethod['Get']), (apps.test_platform.enumeration.RequestMethod['POST'], apps.test_platform.enumeration.RequestMethod['POST']), (apps.test_platform.enumeration.RequestMethod['PUT'], apps.test_platform.enumeration.RequestMethod['PUT']), (apps.test_platform.enumeration.RequestMethod['DELETE'], apps.test_platform.enumeration.RequestMethod['DELETE'])], max_length=255, verbose_name='请求方式'),
        ),
    ]
