# Generated by Django 3.0.6 on 2020-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0003_auto_20200726_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestreport',
            name='is_status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='apitestreportdetail',
            name='is_status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
