# Generated by Django 3.0.6 on 2020-06-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0004_auto_20200616_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasedetail',
            name='checkpoint',
        ),
    ]
