# Generated by Django 3.0.6 on 2020-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0004_auto_20200604_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitestreport',
            name='end_time_stamp',
        ),
        migrations.RemoveField(
            model_name='apitestreport',
            name='excute_time',
        ),
        migrations.RemoveField(
            model_name='apitestreport',
            name='start_time_stamp',
        ),
        migrations.AddField(
            model_name='apitestreport',
            name='time_taken',
            field=models.FloatField(blank=True, null=True, verbose_name='执行使用时间'),
        ),
    ]
