# Generated by Django 3.0.6 on 2020-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0004_auto_20200726_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasedetail',
            name='data',
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='http_body',
            field=models.TextField(default='{}', verbose_name='请求体入参'),
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='parames',
            field=models.TextField(default='{}', verbose_name='请求头入参'),
        ),
    ]
