# Generated by Django 3.0.6 on 2020-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0005_auto_20200605_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestreportdetail',
            name='fail_times',
            field=models.IntegerField(null=True, verbose_name='用例排序顺序'),
        ),
    ]
