# Generated by Django 3.0.6 on 2020-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0005_remove_testcasedetail_checkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasedetail',
            name='parameters_status',
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='expression_status',
            field=models.BooleanField(default=False, verbose_name='表达式状态（0 不启用jsonpath捕捉参数化，1 启用jsonpath捕捉参数化）'),
        ),
    ]
