# Generated by Django 3.0.6 on 2020-07-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0005_auto_20200727_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='http_body',
            new_name='data',
        ),
    ]
