# Generated by Django 3.0.6 on 2020-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0006_auto_20200727_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestreportdetail',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='所属用例id'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='busi_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='所属业务id'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='所属项目id'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='所属项目id'),
        ),
    ]
