# Generated by Django 3.0.6 on 2020-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0006_apitestreportdetail_fail_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='case_sort',
            new_name='sort',
        ),
        migrations.AddField(
            model_name='testcase',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
