# Generated by Django 3.0.6 on 2020-06-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0007_auto_20200606_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='path_id',
            new_name='interface_id',
        ),
    ]
