# Generated by Django 3.0.6 on 2020-07-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0007_auto_20200728_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='creater',
        ),
    ]
