# Generated by Django 3.0.6 on 2020-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0008_auto_20200606_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitestreport',
            name='env',
        ),
        migrations.AddField(
            model_name='apitestreport',
            name='host',
            field=models.CharField(max_length=32, null=True, verbose_name='执行任务环境'),
        ),
    ]
