# Generated by Django 3.0.6 on 2020-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0009_auto_20200607_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestreport',
            name='executor',
            field=models.CharField(max_length=32, null=True, verbose_name='计划执行者'),
        ),
    ]
