# Generated by Django 3.0.6 on 2020-06-07 02:24

import apps.test_platform.enumeration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0010_auto_20200607_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='case_sort',
            new_name='sort',
        ),
        migrations.AlterField(
            model_name='apitestreport',
            name='task_status',
            field=models.CharField(choices=[(apps.test_platform.enumeration.TaskStatus['WAIT'], apps.test_platform.enumeration.TaskStatus['WAIT']), (apps.test_platform.enumeration.TaskStatus['EXECUTION'], apps.test_platform.enumeration.TaskStatus['EXECUTION']), (apps.test_platform.enumeration.TaskStatus['FINISH'], apps.test_platform.enumeration.TaskStatus['FINISH']), (apps.test_platform.enumeration.TaskStatus['FAILSE'], apps.test_platform.enumeration.TaskStatus['FAILSE'])], max_length=32, verbose_name='任务状态（1、等待执行2、执行中3、成功4、失败）'),
        ),
    ]
