# Generated by Django 3.0.6 on 2020-06-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0011_auto_20200607_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestreport',
            name='time_taken',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='执行使用时间'),
        ),
        migrations.AlterField(
            model_name='apitestreportdetail',
            name='end_time_stamp',
            field=models.CharField(max_length=32, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='apitestreportdetail',
            name='excute_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='执行使用时间'),
        ),
        migrations.AlterField(
            model_name='apitestreportdetail',
            name='start_time_stamp',
            field=models.CharField(max_length=32, null=True, verbose_name='开始时间'),
        ),
    ]
