# Generated by Django 3.0.6 on 2020-06-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0012_auto_20200607_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='end_time_stamp',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='start_time_stamp',
            new_name='start_time',
        ),
    ]
