# Generated by Django 3.0.6 on 2020-06-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0013_auto_20200607_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='excute_time',
            new_name='time_taken',
        ),
    ]
