# Generated by Django 3.0.6 on 2020-06-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0014_auto_20200607_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreport',
            old_name='excute_total',
            new_name='total',
        ),
    ]
