# Generated by Django 3.0.6 on 2020-06-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0015_auto_20200607_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='end_time',
            new_name='stop_time',
        ),
    ]
