# Generated by Django 3.0.6 on 2020-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0016_auto_20200607_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasedetail',
            name='fail_times',
            field=models.IntegerField(default=0, verbose_name='失败次数'),
        ),
        migrations.AlterField(
            model_name='testcasedetail',
            name='reconnection_times',
            field=models.IntegerField(default=3, verbose_name='重连次数'),
        ),
        migrations.AlterField(
            model_name='testcasedetail',
            name='wait_time',
            field=models.IntegerField(default=10, verbose_name='最长等待时长'),
        ),
    ]
