# Generated by Django 3.0.6 on 2020-06-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0017_auto_20200608_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='input_parameter',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='output_parameter',
            new_name='response',
        ),
    ]
