# Generated by Django 3.0.6 on 2020-06-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0018_auto_20200608_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestreportdetail',
            old_name='input_header',
            new_name='header',
        ),
    ]
