# Generated by Django 3.0.6 on 2020-06-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0019_auto_20200608_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='input_parameter',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='testcasedetail',
            old_name='input_header',
            new_name='header',
        ),
    ]
