# Generated by Django 3.0.6 on 2020-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0020_auto_20200608_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestreportdetail',
            name='api_name',
            field=models.CharField(max_length=32, null=True, verbose_name='接口名称'),
        ),
        migrations.AddField(
            model_name='apitestreportdetail',
            name='url',
            field=models.CharField(max_length=128, null=True, verbose_name='请求地址'),
        ),
    ]
