# Generated by Django 3.0.6 on 2020-06-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0021_auto_20200608_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasedetail',
            name='fail_times',
        ),
    ]
