# Generated by Django 3.0.6 on 2020-09-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiassert',
            old_name='assert_object',
            new_name='assert_obj',
        ),
        migrations.RenameField(
            model_name='apiassert',
            old_name='assert_value',
            new_name='assert_val',
        ),
    ]
