# Generated by Django 3.0.6 on 2020-09-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0002_auto_20200912_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiassert',
            name='api_model_id',
        ),
        migrations.AddField(
            model_name='apiassert',
            name='data_id',
            field=models.IntegerField(default=0, verbose_name='所属数据id'),
            preserve_default=False,
        ),
    ]
