# Generated by Django 3.0.6 on 2020-11-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0002_auto_20201112_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.A'),
        ),
    ]
