# Generated by Django 3.0.6 on 2020-09-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0003_auto_20200912_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiassert',
            name='model_id',
            field=models.IntegerField(default=0, verbose_name='关联模型id'),
            preserve_default=False,
        ),
    ]
