# Generated by Django 3.0.6 on 2020-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0004_apiassert_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiassert',
            name='aaaa',
            field=models.IntegerField(default=0, verbose_name='所属数据id'),
            preserve_default=False,
        ),
    ]
