# Generated by Django 3.0.6 on 2020-11-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0004_auto_20201112_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='project_id',
            new_name='project',
        ),
    ]
