# Generated by Django 3.0.6 on 2020-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0005_auto_20201112_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='project_id',
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.Project'),
        ),
    ]
