# Generated by Django 3.0.6 on 2020-09-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0005_apiassert_aaaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiassert',
            name='aaaa',
        ),
    ]
