# Generated by Django 3.0.6 on 2020-09-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0006_remove_apiassert_aaaa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '事件表', 'verbose_name_plural': '事件表'},
        ),
        migrations.AlterModelOptions(
            name='eventapirecord',
            options={'verbose_name': '接口事件细节记录', 'verbose_name_plural': '接口事件细节记录'},
        ),
        migrations.AlterModelOptions(
            name='eventapiresult',
            options={'verbose_name': '接口事件结果', 'verbose_name_plural': '接口事件结果'},
        ),
        migrations.RenameField(
            model_name='apicasedatanode',
            old_name='params',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='api',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='apiassert',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='apicasedata',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='apicasedatanode',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='apicasedatanode',
            name='is_expression',
            field=models.BooleanField(default=False, verbose_name='表达式状态：0 不启用jsonpath捕捉参数化\n 1 启用jsonpath捕捉参数化'),
        ),
        migrations.AlterField(
            model_name='apicasemodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='apicasemodel',
            name='is_expression',
            field=models.BooleanField(default=False, verbose_name='表达式状态：0 不启用jsonpath捕捉参数化\n 1 启用jsonpath捕捉参数化'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='eventapirecord',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='eventapiresult',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='host',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='qacase',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
        migrations.AlterField(
            model_name='qaplan',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除：1删除 0未删除'),
        ),
    ]
