# Generated by Django 3.0.6 on 2020-09-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0007_auto_20200930_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventapirecord',
            old_name='params',
            new_name='query',
        ),
    ]
