# Generated by Django 3.0.6 on 2020-11-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0007_auto_20201112_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='project',
            new_name='project_id',
        ),
        migrations.AlterField(
            model_name='apiassert',
            name='data_id',
            field=models.ForeignKey(blank=True, db_column='data_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.Project'),
        ),
        migrations.AlterField(
            model_name='apiassert',
            name='model_id',
            field=models.ForeignKey(blank=True, db_column='model_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.Project'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.Project'),
        ),
    ]
