# Generated by Django 3.0.6 on 2020-11-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0009_auto_20201112_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicasedata',
            name='case_id',
            field=models.ForeignKey(blank=True, db_column='case_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase', verbose_name='所属数据id'),
        ),
    ]
