# Generated by Django 3.0.6 on 2020-11-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0011_auto_20201112_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaplan',
            name='project_id',
        ),
        migrations.AddField(
            model_name='qaplan',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.Project'),
        ),
        migrations.AlterField(
            model_name='apiassert',
            name='data_id',
            field=models.ForeignKey(db_column='data_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.ApiCaseData'),
        ),
        migrations.AlterField(
            model_name='apiassert',
            name='model_id',
            field=models.ForeignKey(db_column='model_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.ApiCaseModel'),
        ),
        migrations.AlterField(
            model_name='apicasedata',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase'),
        ),
        migrations.AlterField(
            model_name='apicasemodel',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase'),
        ),
        migrations.AlterField(
            model_name='eventapirecord',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase'),
        ),
        migrations.AlterField(
            model_name='eventapirecord',
            name='data_id',
            field=models.ForeignKey(db_column='data_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.ApiCaseData'),
        ),
        migrations.AlterField(
            model_name='eventapirecord',
            name='result_id',
            field=models.ForeignKey(db_column='result_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.EventApiResult'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project_id',
            field=models.ForeignKey(blank=True, db_column='project_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.Project'),
        ),
        migrations.AlterField(
            model_name='qacase',
            name='plan_id',
            field=models.ForeignKey(db_column='plan_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaPlan'),
        ),
    ]
