# Generated by Django 3.0.6 on 2020-11-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0012_auto_20201112_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiassert',
            name='data_id',
            field=models.ForeignKey(db_column='data_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.ApiCaseData'),
        ),
        migrations.AlterField(
            model_name='apiassert',
            name='model_id',
            field=models.ForeignKey(db_column='model_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.ApiCaseModel'),
        ),
        migrations.AlterField(
            model_name='apicasedata',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase'),
        ),
        migrations.AlterField(
            model_name='eventapirecord',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase'),
        ),
        migrations.AlterField(
            model_name='eventapirecord',
            name='result_id',
            field=models.ForeignKey(db_column='result_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.EventApiResult'),
        ),
        migrations.AlterField(
            model_name='qacase',
            name='plan_id',
            field=models.ForeignKey(db_column='plan_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaPlan'),
        ),
    ]
