# Generated by Django 3.0.6 on 2020-11-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0013_auto_20201112_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiassert',
            old_name='data_id',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='apiassert',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='apicasedata',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='apicasedatanode',
            old_name='data_id',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='apicasedatanode',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='apicasemodel',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='eventapirecord',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='eventapirecord',
            old_name='data_id',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='eventapirecord',
            old_name='result_id',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='qacase',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
