# Generated by Django 3.0.6 on 2020-11-13 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0014_auto_20201113_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicasemodel',
            name='api_id',
        ),
        migrations.AddField(
            model_name='apicasemodel',
            name='Api',
            field=models.ForeignKey(db_column='api_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qa_platform.QaCase'),
            preserve_default=False,
        ),
    ]
