# Generated by Django 3.0.6 on 2020-11-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0017_auto_20201115_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='content_type',
            field=models.CharField(choices=[('text/html', 'text/html'), ('text/plain', 'text/plain'), ('text/xml', 'text/xml'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('application/json', 'application/json'), ('application/xml', 'application/xml'), ('application/msword', 'application/msword'), ('application/pdf', 'application/pdf'), ('image/gif', 'image/gif'), ('image/jpeg', 'image/jpeg'), ('image/png', 'image/png')], max_length=128, verbose_name='http报文body序列化类型content_type'),
        ),
    ]
