# Generated by Django 3.0.6 on 2020-11-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0018_auto_20201116_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=['GET', 'POST', 'PUT', 'DELETE'], max_length=255, verbose_name='请求方式'),
        ),
    ]
