# Generated by Django 3.0.6 on 2020-11-16 00:12

import apps.qa_platform.enumeration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_platform', '0019_auto_20201116_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[apps.qa_platform.enumeration.HttpMethod['Get'], apps.qa_platform.enumeration.HttpMethod['POST'], apps.qa_platform.enumeration.HttpMethod['PUT'], apps.qa_platform.enumeration.HttpMethod['DELETE']], max_length=255, verbose_name='请求方式'),
        ),
    ]
